config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root to: 'posts#index'

  resources :posts do
    resources :comments
    resources :likes
    resources :charges
  end

end

app/models/comment.rb
class Comment < ActiveRecord::Base

  belongs_to :post
  belongs_to :user

end

app/models/like.rb
class Like < ActiveRecord::Base
  belongs_to :post
end

app/models/post.rb
class Post < ActiveRecord::Base

  has_attached_file :image, :styles => { :medium => "300x300>", :thumb => "100x100>" },
                    :default_url => "/images/:style/missing.png",
                    :storage => :s3,
                    :bucket => ENV['S3_BUCKET_NAME'],
                    :s3_host_name => 's3-eu-west-1.amazonaws.com',
                    :s3_credentials => {
                      :bucket => ENV['S3_BUCKET_NAME'],
                      :access_key_id => ENV['AWS_ACCESS_KEY_ID'],
                      :secret_access_key => ENV['AWS_SECRET_ACCESS_KEY']
                      }



  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  belongs_to :user
  has_many :comments
  has_many :likes

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :posts
  has_many :comments
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @user = current_user
  end

  def create
    @post = Post.find(params[:post_id])
    @amount = @post.price*100

    customer = Stripe::Customer.create(
      :email => 'example@stripe.com',
      :card => params[:stripeToken]
    )

    charge = Stripe::Charge.create(
    :customer     => customer.id,
    :amount       => @amount,
    :description  => 'Rails Stripe Customer',
    :currency     => 'gbp'
    )

  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to charges_path
  end


end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  def new
    @post = Post.find(params[:post_id])
    @comment = Comment.new(user: current_user)
  end

  def create
    @post = Post.find(params[:post_id])
    @post.comments.create((comment_params).merge(user_id: current_user.id))
    redirect_to post_path(@post)
  end

  def comment_params
    params.require(:comment).permit(:content)
  end

end

app/controllers/likes_controller.rb
class LikesController < ApplicationController


  def create
    @post = Post.find(params[:post_id])
    @post.likes.create
    render json: {new_like_count: @post.likes.count}
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController

  def index
    @posts = Post.all
  end

  def show
    @post = Post.find(params[:id])
  end

  def new
    @post = Post.new
  end

  def create
    Post.create(post_params)
    redirect_to '/posts'
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy
    redirect_to  '/posts'
  end

  def edit
    @post = Post.find(params[:id])
  end

  def update
    @post = Post.find(params[:id])
    @post.update(params[:post].permit(:description, :image, :price))
    redirect_to '/posts'
  end

  private

  def post_params
    params.require(:post).permit(:description, :image, :price).merge(user_id: get_user_id)
  end

  def get_user_id
    return current_user.id if user_signed_in?
    return nil
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/likes_helper.rb
module LikesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/charges/create.html.erb
<h2>Thanks, you paid <strong><%= @post.price %></strong>!</h2>

app/views/charges/new.html.erb
<%= form_tag post_charges_path do %>
  <article>
    <label class="amount">
      <span>Amount: £<%= @post.price %></span>
    </label>
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="A pretty picture..."
          data-currency='gbp'
          data-amount="<%= @post.price*100 %>"></script>

<% end %>

app/views/comments/new.html.erb
<%= form_for [@post, @comment] do |f| %>
  <%= f.label :content %>
  <%= f.text_area :content %>
  <%= f.submit 'Comment' %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>InstraOunce</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>



<!-- <nav class="navbar navbar-inverse navbar-fixed-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <a class="navbar-brand" href="#">Project name</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <form class="navbar-form navbar-right" role="form">
            <div class="form-group">
              <input type="text" placeholder="Email" class="form-control">
            </div>
            <div class="form-group">
              <input type="password" placeholder="Password" class="form-control">
            </div>
            <button type="submit" class="btn btn-success">Sign in</button>
          </form>
        </div><!--/.navbar-collapse -->
      </div>
    </nav> -->


  <p class="notice"><%= notice %></p>
  <p class="alert"><%= alert %></p>

  <div class="container">
    <div class="row">
      <div class="col-md-4 col-md-offset-4">


  <% if user_signed_in? %>
    <%= link_to 'Sign Out', destroy_user_session_path, method: :delete %>
  <% else %>
    <%= link_to 'Sign Up', new_user_registration_path %>
    <%= link_to 'Sign In', new_user_session_path %>
  <% end %>
</div>
</div>
</div>

<%= yield %>

</body>
</html>

app/views/layouts/charges.html.erb
<!DOCTYPE html>
<html>
<head>
</head>
<body>
  <%= yield %>
</body>
</html>

app/views/posts/_form.html.erb
<%= form_for @post do |f| %>
  <%= f.label :image %>
  <%= f.file_field :image %>
  <%= f.label :description %>
  <%= f.text_field :description %>
  <%= f.label :price %>
  <%= f.number_field :price, in: 1..50, :placeholder => "£" %>
  <%= f.submit %>
<% end %>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<div class='container'>

<% if user_signed_in? %>
  <%= link_to 'Add a post', new_post_path %>
<% end %>

<% if @posts.any? %>
  <% @posts.each do |post| %>
  <article>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= post.user.email %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
      <% if post.image != nil %>
        <%= image_tag post.image.url(:thumb) %>
      <% end %>
      </div>
    </div>
    <div class="row">
      <div class="col-md-4 col-md-offset-4">
        <%= link_to "#{post.description}", post_path(post) %>
        <%= link_to "Like", post_likes_path(post), class: 'likes-link' %>
        <span class="likes_count"> <%= post.likes.count %> </span> likes
      </div>
    </div>
  </article>
  <% end %>

<% else %>

  No posts yet

<% end %>

</div>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<% if @post.image != nil %>
  <%= image_tag @post.image.url(:medium) %>
<% end %>

<%= @post.description %>

<%= @post.user.email %>


<% if user_signed_in? && current_user.id == @post.user_id %>
  <%= link_to 'Edit post', edit_post_path(@post) %>
  <%= link_to 'Delete post', post_path(@post), method: :delete %>
<% end %>

<%= link_to "Like", post_likes_path(@post), class: 'likes-link' %>
<span class="likes_count"> <%= @post.likes.count %> </span> likes


<%= link_to 'Comment', new_post_comment_path(@post) %>

<%= link_to "Buy Now",  new_post_charge_path(@post), class: "btn btn-success" %>

£<%= @post.price %>

<h4>Comments</h4>
<ul>
  <% if @post.comments.any? %>
    <% @post.comments.each do |comment| %>
      <li><%= comment.content %>
      <% if comment.user_id != nil %>
        (<%= comment.user.email %>)
      <% end %>
      </li>
    <% end %>
  <% end %>
</ul>